version: '3.8'
services:
  app:
    container_name: eventex
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    restart: on-failure:5
    volumes:
      - .:/home/docker/app
    ports:
      - 8000:8000
      - 3000:3000
