# Generated by Django 3.1.7 on 2022-09-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_auto_20220828_2021"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="paid",
            field=models.BooleanField(default=False, verbose_name="pago"),
        ),
    ]
