# Generated by Django 3.1.7 on 2022-12-18 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_auto_20221216_1801"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("E", "Email"), ("P", "Telefone")], max_length=1
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                (
                    "speaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.speaker"
                    ),
                ),
            ],
        ),
    ]
