# Generated by Django 3.1.7 on 2023-02-24 18:31

from django.db import migrations


def copy_src_to_dst(source, destination):
    for src in source.objects.all():
        dst = destination(
            title=src.title,
            start=src.start,
            description=src.description,
            slots=src.slots,
        )
        dst.save()
        dst.speakers.set(src.speakers.all())
        src.delete()


def forward_course_abc_to_mti(apps, schema_editor):
    """
    1. Para cada ABC, instanciar um MTI com todos os atributos.
    2. Salvar MTI.
    3. Associar os Speakers do ABC no MTI.
    4. Deletar o ABC.
    """
    copy_src_to_dst(
        source=apps.get_model("core", "CourseOld"),
        destination=apps.get_model("core", "Course"),
    )


def backward_course_abc_to_mti(apps, schema_editor):
    """
    Faz o caminho inverso da função forward_course_abc_to_mti()
    """
    copy_src_to_dst(
        source=apps.get_model("core", "Course"),
        destination=apps.get_model("core", "CourseOld"),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_course"),
    ]

    operations = [
        migrations.RunPython(forward_course_abc_to_mti, backward_course_abc_to_mti)
    ]
