# Generated by Django 3.1.7 on 2023-02-25 23:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_course_abc_to_mti"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourseOld",
        ),
    ]
